name: Deploy Python Applicaiton to Google Cloud Run

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to google cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud config set run/region us-central1
      
      - name: Build and deploy docker run
        run: |
          docker builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-python-app .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-python-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-python-app \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-python-app \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated